# https://golangci-lint.run/usage/configuration/
linters:
  disable-all: true
  enable:
  - deadcode
  - errcheck
  - gofmt
  - golint
  - gosimple
  - govet
  - ineffassign
  - misspell
  - staticcheck
  - structcheck
  - typecheck
  - unused
  - varcheck
issues:
  exclude-use-default: false
  exclude-rules:
  - path: _test[.]go
    linters:
      - errcheck
      - gosimple
